// Source unique des données des missions scientifiques Wings for Science
// Chaque mission : champs FR (name, country, periode, institution, mission, objectif)
// + champs _en pour les traductions. Utilisé par campagne-scientifique.html
// (tableau + carte Leaflet). Pour ajouter/modifier une mission, éditer UNIQUEMENT ce fichier.

window.WFS_MISSIONS = [
{name:"Daring Lake", country:"CANADA", country_en:"CANADA", lat:64.87, lng:-111.55, periode:"juillet 2017", periode_en:"July 2017", institution:"Daring Lake Tundra Ecosystem Research Station", institution_en:"Daring Lake Tundra Ecosystem Research Station", mission:"Repérage de l'espèce menacée des Plongeons à bec blanc (Gavia adamsii)", mission_en:"Tracking the endangered Yellow-billed Loon (Gavia adamsii)", objectif:"Comptage afin d'alimenter le dossier de protection de cette espèce menacée et sous-documentée", objectif_en:"Census feeding the conservation case for this endangered and under-documented species", links:{}},
{name:"Morne à l'Eau", country:"GUADELOUPE", country_en:"GUADELOUPE", lat:16.37, lng:-61.52, periode:"janvier 2017", periode_en:"January 2017", institution:"Commune de Morne à l'Eau", institution_en:"Municipality of Morne à l'Eau", mission:"Orthophotographie géoréférencée des frontières des îles entourant la mangrove", mission_en:"Georeferenced orthophotography of island borders surrounding the mangrove", objectif:"Étude de l'érosion des îles et du rôle de la mangrove", objectif_en:"Study of island erosion and the role of the mangrove", links:{}},
{name:"Paramaribo", country:"SURINAM", country_en:"SURINAME", lat:5.85, lng:-55.2, periode:"novembre 2016", periode_en:"November 2016", institution:"Green Heritage Fund Suriname", institution_en:"Green Heritage Fund Suriname", mission:"Photographie du littoral et recherche de dauphins de Guyane", mission_en:"Coastal photography and tracking of Guiana dolphins", objectif:"Étude de l'impact de l'érosion des plages sur la biodiversité + suivi des dauphins qui quittent la rivière", objectif_en:"Assessing the impact of beach erosion on biodiversity + tracking dolphins leaving the river", links:{}},
{name:"Amana", country:"GUYANE FRANÇAISE", country_en:"FRENCH GUIANA", lat:5.79, lng:-53.68, periode:"octobre 2016", periode_en:"October 2016", institution:"Réserve Naturelle de l'Amana", institution_en:"Amana Nature Reserve", mission:"Couverture photographique de la réserve", mission_en:"Photographic coverage of the reserve", objectif:"Exploration des différents biotopes à la frontière de la réserve et étude de la biodiversité de cette savane humide", objectif_en:"Exploring the different biotopes at the reserve's borders and studying the biodiversity of this wetland savannah", links:{}},
{name:"Volcan Huaynaputina", name_en:"Huaynaputina Volcano", country:"PÉROU", country_en:"PERU", lat:-16.61, lng:-70.85, periode:"septembre 2016", periode_en:"September 2016", institution:"INGEMMET, CEREMA, Univ. de la Réunion", institution_en:"INGEMMET, CEREMA, Univ. de la Réunion", mission:"Prospection géophysique autour du cratère volcanique à 5 000 mètres", mission_en:"Geophysical survey around the 5,000-metre volcanic crater", objectif:"Détection de nouvelles preuves archéologiques de villages enfouis après l'éruption inca du Huaynaputina en 1600", objectif_en:"Detecting new archaeological evidence of villages buried after the 1600 Huaynaputina Inca eruption", links:{}},
{name:"Rio Paraná", country:"BRÉSIL", country_en:"BRAZIL", lat:-22.42, lng:-47.65, periode:"août 2016", periode_en:"August 2016", institution:"Área de Proteção Ambiental das Ilhas e Várzeas do Rio Paraná - ICMBio", institution_en:"Área de Proteção Ambiental das Ilhas e Várzeas do Rio Paraná - ICMBio", mission:"Prélèvements d'eau, localisation des harpies, photographie de la biodiversité dans les différents biotopes", mission_en:"Water sampling, harpy eagle tracking, photography of biodiversity across biotopes", objectif:"Meilleure protection et connaissance de la région et de ses différents biotopes", objectif_en:"Better protection and understanding of the region and its different biotopes", links:{}},
{name:"Bañado La Estrella", country:"ARGENTINE", country_en:"ARGENTINA", lat:-23.9, lng:-62.3, periode:"juillet 2016", periode_en:"July 2016", institution:"Fundación ProYungas", institution_en:"Fundación ProYungas", mission:"Identification des biotopes spécifiques et des zones de biodiversité intense le long de la rivière Bermejo", mission_en:"Identifying specific biotopes and biodiversity hotspots along the Bermejo River", objectif:"Création d'une nouvelle zone naturelle préservée et de la première zone protégée fluviale", objectif_en:"Creating a new protected natural area and the first protected river zone", links:{}},
{name:"Trelew", country:"ARGENTINE", country_en:"ARGENTINA", lat:-43.25, lng:-65.31, periode:"juillet 2016", periode_en:"July 2016", institution:"Museum of Paleontology Egidio Feruglio", institution_en:"Egidio Feruglio Palaeontology Museum", mission:"Localisation, photographie et DEM de vastes zones de Rizolithes Fossiles", mission_en:"Locating, photographing and DEM of vast fossil rhizolite areas", objectif:"Découverte de nouvelles zones de fossiles rizolithes", objectif_en:"Discovering new fossil rhizolite areas", links:{video:"https://www.youtube-nocookie.com/embed/Vl6TSsgTFT4", video_title:"Les pierres précieuses des aborigènes", video_title_en:"The Aboriginal precious stones"}},
{name:"Laguna Epecuén", country:"ARGENTINE", country_en:"ARGENTINA", lat:-37.13, lng:-62.89, periode:"juin 2016", periode_en:"June 2016", institution:"Reserva Natural Municipal de la Laguna Epecuén", institution_en:"Reserva Natural Municipal de la Laguna Epecuén", mission:"Comptabilisation et identification des flamants roses et des zones d'artemia salina", mission_en:"Counting and identifying flamingos and Artemia salina areas", objectif:"Documentation du milieu naturel des flamants roses", objectif_en:"Documenting the natural habitat of flamingos", links:{blog:"actu.html#epecuen"}},
{name:"Osorno", country:"CHILI", country_en:"CHILE", lat:-40.57, lng:-73.13, periode:"mai 2016", periode_en:"May 2016", institution:"Colegio Emprender", institution_en:"Colegio Emprender", mission:"Documentation photographique de la rivière Rahue pour identifier les points d'anthropisation et de pollution", mission_en:"Photographic documentation of the Rahue River to identify anthropogenic and pollution hotspots", objectif:"Localisation des points de pollution fluviale potentiels afin de poursuivre avec des prélèvements", objectif_en:"Locating potential river pollution sites for further sampling", links:{}},
{name:"Puerto Tranquilo", country:"CHILI", country_en:"CHILE", lat:-46.62, lng:-72.67, periode:"avril 2016", periode_en:"April 2016", institution:"Pontificia Universidad Católica de Chile", institution_en:"Pontificia Universidad Católica de Chile", mission:"Exploration d'un lac inconnu : modèle 3D et prélèvement d'échantillons de sol / eau / végétation", mission_en:"Exploring an uncharted lake: 3D modelling and sampling of soil / water / vegetation", objectif:"Meilleure compréhension de la biodiversité et de la topographie afin de déterminer les futurs usages de cette terre inaccessible", objectif_en:"Better understanding of biodiversity and topography to inform future use of this remote land", links:{}},
{name:"Côte chilienne", name_en:"Chilean Coast", country:"CHILI", country_en:"CHILE", lat:-33.45, lng:-70.67, periode:"mars 2016", periode_en:"March 2016", institution:"Centro de Estudios para la Conservación de Ecosistemas Marinos", institution_en:"Centro de Estudios para la Conservación de Ecosistemas Marinos", mission:"Identification des différents types de dauphins (esp. dauphins chiliens) et leur habitat", mission_en:"Identifying different dolphin species (esp. Chilean dolphins) and their habitats", objectif:"Meilleure compréhension des lieux d'habitat des dauphins chiliens", objectif_en:"Better understanding of Chilean dolphin habitats", links:{}},
{name:"Glacier Upsala", name_en:"Upsala Glacier", country:"ARGENTINE", country_en:"ARGENTINA", lat:-49.87, lng:-73.25, periode:"février 2016", periode_en:"February 2016", institution:"Glaciarium / Pr. Pedro Skvarca", institution_en:"Glaciarium / Prof. Pedro Skvarca", mission:"Modèle 3D du front du glacier Upsala et glissement de terrain", mission_en:"3D model of the Upsala glacier front and landslide", objectif:"Étude du retrait du glacier et du tsunami provoqué par le glissement de terrain", objectif_en:"Studying glacier retreat and the tsunami triggered by the landslide", links:{video:"https://www.youtube-nocookie.com/embed/MrijzVMZvg0", video_title:"L'île secrète des gazelles", video_title_en:"The secret gazelle island"}},
{name:"Ittoqqortoormiit", country:"GROENLAND", country_en:"GREENLAND", lat:70.48, lng:-21.97, periode:"novembre 2014", periode_en:"November 2014", institution:"Asiaq", institution_en:"Asiaq", mission:"Documentation photographique d'un glacier", mission_en:"Photographic documentation of a glacier", objectif:"Étude transdisciplinaire sur le changement climatique", objectif_en:"Cross-disciplinary climate change study", links:{}},
{name:"Kulusuk", country:"GROENLAND", country_en:"GREENLAND", lat:65.57, lng:-37.18, periode:"septembre 2014", periode_en:"September 2014", institution:"Université de Brest", institution_en:"University of Brest", mission:"Documentation 3D et transects photographiques d'un archipel isolé", mission_en:"3D documentation and photographic transects of a remote archipelago", objectif:"Meilleure compréhension du contexte géologique", objectif_en:"Better understanding of the geological context", links:{}},
{name:"Samos", country:"GRÈCE", country_en:"GREECE", lat:37.75, lng:26.98, periode:"mai 2013", periode_en:"May 2013", institution:"Archipelagos Institute of Marine Conservation", institution_en:"Archipelagos Institute of Marine Conservation", mission:"Cartographie de la posidonie et étude des mammifères marins", mission_en:"Mapping Posidonia seagrass and studying marine mammals", objectif:"Identification des impacts anthropiques sur la biodiversité marine", objectif_en:"Identifying anthropogenic impacts on marine biodiversity", links:{video:"https://www.youtube-nocookie.com/embed/6qm-my9bBrE", video_title:"Sous les vagues grecques, un trésor invisible", video_title_en:"Beneath the Greek waves, an invisible treasure"}},
{name:"Jerash / Qasr Bshir", country:"JORDANIE", country_en:"JORDAN", lat:29.57, lng:35.42, periode:"avril 2013", periode_en:"April 2013", institution:"Institut Français du Proche Orient", institution_en:"French Institute of the Near East", mission:"Cartographie & DEM des sites archéologiques, prospection archéologique, identification de sites inconnus", mission_en:"Mapping & DEM of archaeological sites, survey, identification of unknown sites", objectif:"Identification de nouveaux sites archéologiques et cartographie des sites déjà connus", objectif_en:"Identifying new archaeological sites and mapping known ones", links:{video:"https://www.youtube-nocookie.com/embed/0N4Cwn5kRLA", video_title:"Les cités englouties par le désert", video_title_en:"Cities swallowed by the desert"}},
{name:"Krakatoa", country:"INDONÉSIE", country_en:"INDONESIA", lat:-6.1, lng:105.42, periode:"mars 2013", periode_en:"March 2013", institution:"Center for Volcanology and Geological Hazard Mitigation", institution_en:"Center for Volcanology and Geological Hazard Mitigation", mission:"Échantillonnage et DEM SO₂ du dôme volcanique du Krakatoa et des autres volcans de la chaîne", mission_en:"SO₂ sampling and DEM of the Krakatau volcanic dome and other volcanoes in the chain", objectif:"Analyse des flux de gaz volcanique", objectif_en:"Volcanic gas flux analysis", links:{video:"https://www.youtube-nocookie.com/embed/bRG5kaBJxj8", video_title:"Vivre sur un volcan en fusion", video_title_en:"Living on a molten volcano"}},
{name:"Philip Island", country:"AUSTRALIE", country_en:"AUSTRALIA", lat:-38.49, lng:145.23, periode:"février 2013", periode_en:"February 2013", institution:"Phillip Island Nature Park", institution_en:"Phillip Island Nature Park", mission:"Film infrarouge", mission_en:"Infrared filming", objectif:"Meilleure compréhension de la vie nocturne des pingouins", objectif_en:"Better understanding of penguins' nocturnal life", links:{video:"https://www.youtube-nocookie.com/embed/c_LurzAX3B8", video_title:"Les manchots face à l'océan", video_title_en:"Penguins facing the ocean"}},
{name:"Lac Rupanco", name_en:"Lake Rupanco", country:"CHILI", country_en:"CHILE", lat:-40.8, lng:-72.55, periode:"décembre 2012", periode_en:"December 2012", institution:"Centro para la Protección Ambiental del Lago Rupanco", institution_en:"Centro para la Protección Ambiental del Lago Rupanco", mission:"Photographie aérienne systématique des bordures du lac", mission_en:"Systematic aerial photography of the lake shoreline", objectif:"Analyse et protection de la biodiversité du lac Rupanco", objectif_en:"Analysis and protection of Lake Rupanco biodiversity", links:{}},
{name:"Près de Santiago", name_en:"Near Santiago", country:"CHILI", country_en:"CHILE", lat:-33.45, lng:-70.67, periode:"novembre 2012", periode_en:"November 2012", institution:"Fogquest Chile", institution_en:"Fogquest Chile", mission:"Identification des zones sèches, brumeuses et habitées", mission_en:"Identifying dry, foggy and inhabited areas", objectif:"Localisation des futures zones de collecte de brouillard", objectif_en:"Locating future fog-harvesting areas", links:{video:"https://www.youtube-nocookie.com/embed/T-MEQItRR5s", video_title:"L'eau qui tombe du ciel pour sauver des vies", video_title_en:"Water from the sky that saves lives"}},
{name:"Caral", country:"PÉROU", country_en:"PERU", lat:-10.89, lng:-77.52, periode:"octobre 2012", periode_en:"October 2012", institution:"Zona Arqueológica Caral", institution_en:"Zona Arqueológica Caral", mission:"Prospection archéologique — Découverte de nouveaux sites", mission_en:"Archaeological survey — Discovery of new sites", objectif:"Meilleure compréhension du site de Caral", objectif_en:"Better understanding of the Caral site", links:{video:"https://www.youtube-nocookie.com/embed/d_AuJyDclMM", video_title:"Caral, la civilisation oubliée", video_title_en:"Caral, the forgotten civilisation"}},
{name:"Ouannary", country:"GUYANE FRANÇAISE", country_en:"FRENCH GUIANA", lat:4.1, lng:-51.85, periode:"septembre 2012", periode_en:"September 2012", institution:"Institut de Recherche pour le Développement", institution_en:"Research Institute for Development", mission:"Photographie cartographique de la zone « Pointe Béhague »", mission_en:"Mapping photography of the “Pointe Béhague” area", objectif:"Étude de la mangrove", objectif_en:"Mangrove study", links:{}},
{name:"Archipel de Mingan", name_en:"Mingan Archipelago", country:"CANADA", country_en:"CANADA", lat:50.28, lng:-63.62, periode:"août 2012", periode_en:"August 2012", institution:"Mingan Island Cetacean Study", institution_en:"Mingan Island Cetacean Study", mission:"Documentation photographique de la population de cétacés", mission_en:"Photographic documentation of the cetacean population", objectif:"Étude des cétacés de la rivière Saint-Laurent", objectif_en:"Study of Saint Lawrence River cetaceans", links:{video:"https://www.youtube-nocookie.com/embed/pQsgaB1oVDM", video_title:"À la rescousse des géants des mers", video_title_en:"Rescuing the giants of the seas"}},
{name:"Québec", name_en:"Quebec", country:"CANADA", country_en:"CANADA", lat:46.81, lng:-71.21, periode:"juillet 2012", periode_en:"July 2012", institution:"Institut National d'Optique", institution_en:"National Optics Institute", mission:"Documentation infrarouge d'une forêt", mission_en:"Infrared documentation of a forest", objectif:"Étude de l'état de santé et du niveau de chlorophylle", objectif_en:"Assessing forest health and chlorophyll levels", links:{}},
{name:"Narsarsuaq", country:"GROENLAND", country_en:"GREENLAND", lat:61.16, lng:-45.42, periode:"juillet 2012", periode_en:"July 2012", institution:"Asiaq", institution_en:"Asiaq", mission:"Documentation photographique d'un glacier", mission_en:"Photographic documentation of a glacier", objectif:"Étude transdisciplinaire sur le changement climatique", objectif_en:"Cross-disciplinary climate change study", links:{}},
{name:"Surtsey", country:"ISLANDE", country_en:"ICELAND", lat:63.3, lng:-20.6, periode:"juin 2012", periode_en:"June 2012", institution:"Umhverfisstofnun — Environment Agency of Iceland", institution_en:"Umhverfisstofnun — Environment Agency of Iceland", mission:"DEM de l'île de Surtsey", mission_en:"DEM of Surtsey island", objectif:"Étude de l'érosion de l'île et de la contamination des formes de vie", objectif_en:"Study of island erosion and life-form contamination", links:{}},
{name:"Elliðaey", country:"ISLANDE", country_en:"ICELAND", lat:63.43, lng:-20.27, periode:"juin 2012", periode_en:"June 2012", institution:"Náttúrustofa Suðurlands — Icelandic Institute of Natural History", institution_en:"Náttúrustofa Suðurlands — Icelandic Institute of Natural History", mission:"DEM des îles Ystiklettur et Elliðaey", mission_en:"DEM of Ystiklettur and Elliðaey islands", objectif:"Analyse de l'habitat des macareux", objectif_en:"Puffin habitat analysis", links:{}},
{name:"Luxembourg", country:"LUXEMBOURG", country_en:"LUXEMBOURG", lat:49.61, lng:6.13, periode:"mai 2012", periode_en:"May 2012", institution:"Université du Luxembourg", institution_en:"University of Luxembourg", mission:"DEM du centre-ville et centre européen", objectif:"Étude d'urbanisme", mission_en:"DEM of the city centre and European district", objectif_en:"Urban planning study", links:{}},
{name:"Stromboli & Vulcano", country:"ITALIE", country_en:"ITALY", lat:38.79, lng:15.21, periode:"janvier 2011", periode_en:"January 2011", institution:"Laboratoire Magmas Volcans (LMV)", institution_en:"Magmas and Volcanoes Laboratory (LMV)", mission:"DEM du volcan Stromboli et de l'île de Vulcano", mission_en:"DEM of Stromboli volcano and Vulcano island", objectif:"Volcanologie", objectif_en:"Volcanology", links:{}},
{name:"Clermont-Ferrand", country:"FRANCE", country_en:"FRANCE", lat:45.77, lng:3.09, periode:"octobre 2011", periode_en:"October 2011", institution:"LSCE, Laboratoire des Sciences du Climat et de l'Environnement", institution_en:"LSCE, Climate and Environmental Sciences Laboratory", mission:"Test d'échantillonnage de carbone-suie", mission_en:"Black-carbon sampling test", objectif:"Test d'échantillonnage", objectif_en:"Sampling feasibility test", links:{}},
{name:"Tanna — Yasur", country:"VANUATU", country_en:"VANUATU", lat:-19.52, lng:169.27, periode:"septembre 2011", periode_en:"September 2011", institution:"Laboratoire Magmas Volcans (LMV)", institution_en:"Magmas and Volcanoes Laboratory (LMV)", mission:"Modélisation 3D du dôme résurgent Yasur sur le volcan Yenkahe", mission_en:"3D modelling of the Yasur resurgent dome on Yenkahe volcano", objectif:"Volcanologie", objectif_en:"Volcanology", links:{}},
{name:"Noyon", country:"FRANCE", country_en:"FRANCE", lat:49.58, lng:3.0, periode:"juin 2011", periode_en:"June 2011", institution:"INRAP", institution_en:"INRAP", mission:"Cartographie des sites archéologiques — Découverte d'une nouvelle villa romaine « La mare aux Canards »", mission_en:"Archaeological site mapping — Discovery of a new Roman villa “La mare aux Canards”", objectif:"Cartographie et archéologie", objectif_en:"Mapping and archaeology", links:{}},
{name:"Antarctique", name_en:"Antarctica", country:"ANTARCTIQUE", country_en:"ANTARCTICA", lat:-75.0, lng:0.0, periode:"novembre 2010", periode_en:"November 2010", institution:"LSCE - ORA (Observer, Relever, Analyser)", institution_en:"LSCE - ORA (Observe, Record, Analyse)", mission:"Premier vol d'une sonde météo ballon solaire (atteint 40 000 ft)", mission_en:"First flight of a solar weather balloon probe (reached 40,000 ft)", objectif:"Test de faisabilité", objectif_en:"Feasibility test", links:{}}
];
