(function() {
  var posts = [
    "1er-vol-1er-succes.html",
    "1ere-reconstruction-ce-n-est-qu-un-debut.html",
    "1ers-resultats.html",
    "a-new-flight-test-in-slovenia-patrol-in-the-alps.html",
    "aircraft-back-new-sponsor.html",
    "arrives-a-port-vila.html",
    "bad-weather-instead-of-laos-we-go-to-myanmar.html",
    "bientot-le-depart-sur-le-stromboli.html",
    "bienvenue-a-l-ecole-du-parc-hosingen-welcome-to-hosingen-sch.html",
    "bonne-annee-2017.html",
    "bye-bye-l-avion-take-care-for-your-trip-to-australia.html",
    "c-est-gagne-dinosaur-footprints-soon.html",
    "ca-chauffe.html",
    "cette-fois-on-y-va.html",
    "cette-semaine-au-salon-du-bourget.html",
    "conference-avec-michel-brunet.html",
    "conference-par-l-inrap.html",
    "dernier-jour-du-salon-international-du-bourget.html",
    "derniere-preparation.html",
    "des-nouvelles-argentines.html",
    "deux-magazines.html",
    "diversion-due-to-bad-visibility-but-nice-fishing-system.html",
    "dragon-de-komodo-komodo-dragons.html",
    "drawings-of-college-kids-dessins-des-enfants-rencontres.html",
    "eclipse-totale.html",
    "emirats-arabes-unis-arabie-saoudite.html",
    "essayage-de-l-equipement-de-survie.html",
    "et-c-est-parti.html",
    "first-flight-in-the-plane-premier-vol-test.html",
    "flights-over-luxembourg-city-survol-de-la-ville-du-luxembour.html",
    "flying-again-nous-revoici-en-vol.html",
    "flying-demonstration-demonstration-en-vol.html",
    "friday-at-the-paris-air-show-vendredi-au-bourget.html",
    "go-go-go.html",
    "greenlandic-album-photos-du-groenland.html",
    "gulf-countries-now-at-1st-the-united-arab-emirates.html",
    "here-there-are-the-dinosaurs-footprints.html",
    "huge-discovery-in-caral-decouverte-importante-a-caral.html",
    "hyenas-and-arab-oryx-in-a-protected-refuge-and-artificial-is.html",
    "hyenes-et-oryx-emirats.html",
    "journee-princiere.html",
    "kulusuk.html",
    "kuujjuaq-canada.html",
    "l-essentiel-newspaper.html",
    "land-on-the-road-done.html",
    "landing-at-the-international-paris-air-show-arrivee-au-salon.html",
    "last-but-not-least-meteorite-crater.html",
    "last-night-in-a-bus-listening-to-guitar.html",
    "le-ministere-de-l-education-au-luxembourg-apporte-son-soutie.html",
    "lemonde-uses-our-picture.html",
    "les-eleves-etaient-la.html",
    "luxembourg-3d-city.html",
    "mad-max-6.html",
    "maori-goodbye-for-the-gloworms.html",
    "meeting-beringer.html",
    "mission-au-surinam-paresseux.html",
    "mission-bresil-buritis-parana.html",
    "mission-exploration-decouverte-chili.html",
    "mission-forets-fossilisees-tango.html",
    "mission-glacier-et-tsunami.html",
    "mission-guyane-biodiversite.html",
    "mission-pilaga.html",
    "new-attendees-for-the-departure-nouveaux-invites-pour-le-dep.html",
    "new-media-coverage-la-presse-nous-suit.html",
    "new-sponsor-cnes.html",
    "new-supports-in-luxembourg-nouveaux-soutiens-officiels-au-lu.html",
    "nous-allons-essayer-de-vous-informer.html",
    "nouveau-depart.html",
    "nouveau-volcan-nouvelle-aventure.html",
    "nouvelle-collection-photos.html",
    "now-testing-survival-gear-carefull-for.html",
    "on-a-survole-la-terre-episode-1-islande-our-movie-about-icel.html",
    "on-a-survole-la-terre-episode-2-le-chili-2nd-movie-about-chi.html",
    "on-rentre-vers-port-vila.html",
    "partenariat-avec-l-eso.html",
    "petit-souci.html",
    "princely-luxemburgish-afternoon-apres-midi-princiere-luxembo.html",
    "programme-de-la-journee.html",
    "quand-faut-y-aller.html",
    "quelques-chiffres.html",
    "question-volume.html",
    "question-where-ou-est-ce-que-cette-photo-a-ete-prise.html",
    "radio.html",
    "redcloud-le-teaser.html",
    "rencontre-de-l-equipe-de-l-ecole-jean-jaures-meeting-with-je.html",
    "reportage-sur-la-presse-canada-du-20-juillet.html",
    "rtl-tv-reportage-6min.html",
    "rtl.html",
    "sad-news.html",
    "saudi-arabia.html",
    "seals-phoques.html",
    "shark-vs-whale-requin-contre-baleine.html",
    "smoky-mountain.html",
    "st-marteen-yacht-club.html",
    "surtsey-island-3d-iceland-islande.html",
    "take-off-from-westman-decollage-depuis-westman-en-islande.html",
    "the-answer-la-reponse.html",
    "the-end-of-the-int-paris-air-show-le-salon-du-bourget-c-est-.html",
    "tous-engages-pour-la-science.html",
    "tout-n-est-pas-perdu-there-is-hope.html",
    "trees-in-amazon-forest.html",
    "tribune-confinement.html",
    "underwater-snorkling.html",
    "video-from-ariel-puerto-rico.html",
    "vol-d-aujourd-hui.html",
    "vol-de-demonstration-au-salon-du-bourget.html",
    "volcan-by-night.html",
    "wallaby.html",
    "water-festival-in-yangoon.html",
    "we-fly-over-these-hand-made-artificial-islands-and-this-bigg.html",
    "wednesday-at-the-int-paris-air-show-mercredi-au-salon-du-bou.html",
    "welcome-in-jordan.html",
    "whale-in-mingan-une-baleine-a-mingan.html",
  ];
  var current = location.pathname.split('/').pop();
  var idx = posts.indexOf(current);
  if (idx === -1) return;
  var nav = document.createElement('div');
  nav.className = 'post-nav-arrows';
  var left = document.createElement('a');
  left.href = '../actu.html';
  left.className = 'post-nav-arrow post-nav-left';
  left.innerHTML = '&#8592;';
  left.title = 'Carnet de route';
  nav.appendChild(left);
  if (idx < posts.length - 1) {
    var right = document.createElement('a');
    right.href = posts[idx + 1];
    right.className = 'post-nav-arrow post-nav-right';
    right.innerHTML = '&#8594;';
    right.title = 'Article suivant';
    nav.appendChild(right);
  }
  document.body.appendChild(nav);
})();
